//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Message.proto
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3")]
  public partial class Vector3 : global::ProtoBuf.IExtensible
  {
    public Vector3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CLConnect")]
  public partial class CLConnect : global::ProtoBuf.IExtensible
  {
    public CLConnect() {}
    
    private int _client_version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"client_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int client_version
    {
      get { return _client_version; }
      set { _client_version = value; }
    }
    private string _device;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"device", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device
    {
      get { return _device; }
      set { _device = value; }
    }
    private int _operator_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"operator_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int operator_id
    {
      get { return _operator_id; }
      set { _operator_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageLogin")]
  public partial class MessageLogin : global::ProtoBuf.IExtensible
  {
    public MessageLogin() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagePlayerData")]
  public partial class MessagePlayerData : global::ProtoBuf.IExtensible
  {
    public MessagePlayerData() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private Vector3 _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector3 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private int _mapID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mapID
    {
      get { return _mapID; }
      set { _mapID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageRefreshPosition")]
  public partial class MessageRefreshPosition : global::ProtoBuf.IExtensible
  {
    public MessageRefreshPosition() {}
    
    private Vector3 _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector3 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagePlayerMove")]
  public partial class MessagePlayerMove : global::ProtoBuf.IExtensible
  {
    public MessagePlayerMove() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private Vector3 _curPos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"curPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector3 curPos
    {
      get { return _curPos; }
      set { _curPos = value; }
    }
    private Vector3 _targetPos = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"targetPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3 targetPos
    {
      get { return _targetPos; }
      set { _targetPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageRequestChat")]
  public partial class MessageRequestChat : global::ProtoBuf.IExtensible
  {
    public MessageRequestChat() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageResponseChat")]
  public partial class MessageResponseChat : global::ProtoBuf.IExtensible
  {
    public MessageResponseChat() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagePlayerEnter")]
  public partial class MessagePlayerEnter : global::ProtoBuf.IExtensible
  {
    public MessagePlayerEnter() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private Vector3 _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector3 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagePlayerExit")]
  public partial class MessagePlayerExit : global::ProtoBuf.IExtensible
  {
    public MessagePlayerExit() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageOtherPlayerMove")]
  public partial class MessageOtherPlayerMove : global::ProtoBuf.IExtensible
  {
    public MessageOtherPlayerMove() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private Vector3 _srcPos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"srcPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector3 srcPos
    {
      get { return _srcPos; }
      set { _srcPos = value; }
    }
    private Vector3 _targetPos = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"targetPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3 targetPos
    {
      get { return _targetPos; }
      set { _targetPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageNearPlayerMoveUpdate")]
  public partial class MessageNearPlayerMoveUpdate : global::ProtoBuf.IExtensible
  {
    public MessageNearPlayerMoveUpdate() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private Vector3 _pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vector3 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageErrorCode")]
  public partial class MessageErrorCode : global::ProtoBuf.IExtensible
  {
    public MessageErrorCode() {}
    
    private int _errorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_ID")]
    public enum MSG_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_C2S_REQUEST_LOGIN", Value=10001)]
      ID_C2S_REQUEST_LOGIN = 10001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_S2C_PLAYER_DATA", Value=20001)]
      ID_S2C_PLAYER_DATA = 20001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_C2S_REFRESH_POSITION", Value=20002)]
      ID_C2S_REFRESH_POSITION = 20002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_C2S_PLAYER_MOVE", Value=20003)]
      ID_C2S_PLAYER_MOVE = 20003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_C2S_REQUEST_CHAT", Value=30001)]
      ID_C2S_REQUEST_CHAT = 30001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_S2C_RESPONSE_CHAT", Value=30002)]
      ID_S2C_RESPONSE_CHAT = 30002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_S2C_PLAYER_ENTER", Value=40001)]
      ID_S2C_PLAYER_ENTER = 40001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_S2C_PLAYER_EXIT", Value=40002)]
      ID_S2C_PLAYER_EXIT = 40002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_S2C_OTHER_PLAYER_MOVE", Value=40003)]
      ID_S2C_OTHER_PLAYER_MOVE = 40003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_S2C_NEAR_PLAYER_MOVE_UPDATE", Value=40004)]
      ID_S2C_NEAR_PLAYER_MOVE_UPDATE = 40004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_S2C_ERROR", Value=100001)]
      ID_S2C_ERROR = 100001
    }
  
}