//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Message.proto
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErrorMessage")]
  public partial class ErrorMessage : global::ProtoBuf.IExtensible
  {
    public ErrorMessage() {}
    
    private string _errorReason;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorReason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string errorReason
    {
      get { return _errorReason; }
      set { _errorReason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartBeatReq")]
  public partial class HeartBeatReq : global::ProtoBuf.IExtensible
  {
    public HeartBeatReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartBeatRes")]
  public partial class HeartBeatRes : global::ProtoBuf.IExtensible
  {
    public HeartBeatRes() {}
    
    private int _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _racist;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"racist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int racist
    {
      get { return _racist; }
      set { _racist = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRes")]
  public partial class LoginRes : global::ProtoBuf.IExtensible
  {
    public LoginRes() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FormationReq")]
  public partial class FormationReq : global::ProtoBuf.IExtensible
  {
    public FormationReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FormationRes")]
  public partial class FormationRes : global::ProtoBuf.IExtensible
  {
    public FormationRes() {}
    
    private int _position0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position0", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position0
    {
      get { return _position0; }
      set { _position0 = value; }
    }
    private int _position1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position1
    {
      get { return _position1; }
      set { _position1 = value; }
    }
    private int _position2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"position2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position2
    {
      get { return _position2; }
      set { _position2 = value; }
    }
    private int _position3;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"position3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position3
    {
      get { return _position3; }
      set { _position3 = value; }
    }
    private int _position4;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"position4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position4
    {
      get { return _position4; }
      set { _position4 = value; }
    }
    private int _position5;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"position5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position5
    {
      get { return _position5; }
      set { _position5 = value; }
    }
    private readonly global::System.Collections.Generic.List<ArmyMessage> _armys = new global::System.Collections.Generic.List<ArmyMessage>();
    [global::ProtoBuf.ProtoMember(7, Name=@"armys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ArmyMessage> armys
    {
      get { return _armys; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArmyMessage")]
  public partial class ArmyMessage : global::ProtoBuf.IExtensible
  {
    public ArmyMessage() {}
    
    private int _armyTemplateId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"armyTemplateId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int armyTemplateId
    {
      get { return _armyTemplateId; }
      set { _armyTemplateId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _atk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private int _def;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _round;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int round
    {
      get { return _round; }
      set { _round = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _describe;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string describe
    {
      get { return _describe; }
      set { _describe = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FormationSaveReq")]
  public partial class FormationSaveReq : global::ProtoBuf.IExtensible
  {
    public FormationSaveReq() {}
    
    private int _position0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position0", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position0
    {
      get { return _position0; }
      set { _position0 = value; }
    }
    private int _position1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position1
    {
      get { return _position1; }
      set { _position1 = value; }
    }
    private int _position2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"position2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position2
    {
      get { return _position2; }
      set { _position2 = value; }
    }
    private int _position3;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"position3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position3
    {
      get { return _position3; }
      set { _position3 = value; }
    }
    private int _position4;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"position4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position4
    {
      get { return _position4; }
      set { _position4 = value; }
    }
    private int _position5;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"position5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position5
    {
      get { return _position5; }
      set { _position5 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FormationSaveRes")]
  public partial class FormationSaveRes : global::ProtoBuf.IExtensible
  {
    public FormationSaveRes() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleMatchReq")]
  public partial class BattleMatchReq : global::ProtoBuf.IExtensible
  {
    public BattleMatchReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleMatchRes")]
  public partial class BattleMatchRes : global::ProtoBuf.IExtensible
  {
    public BattleMatchRes() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleMatchSyn")]
  public partial class BattleMatchSyn : global::ProtoBuf.IExtensible
  {
    public BattleMatchSyn() {}
    
    private int _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int success
    {
      get { return _success; }
      set { _success = value; }
    }
    private PlayerMessage _playerInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PlayerMessage playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerMessage")]
  public partial class PlayerMessage : global::ProtoBuf.IExtensible
  {
    public PlayerMessage() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _racist;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"racist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int racist
    {
      get { return _racist; }
      set { _racist = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartBattleReq")]
  public partial class StartBattleReq : global::ProtoBuf.IExtensible
  {
    public StartBattleReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartBattleRes")]
  public partial class StartBattleRes : global::ProtoBuf.IExtensible
  {
    public StartBattleRes() {}
    
    private int _maxHp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _maxMagic;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxMagic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxMagic
    {
      get { return _maxMagic; }
      set { _maxMagic = value; }
    }
    private int _magic;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"magic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magic
    {
      get { return _magic; }
      set { _magic = value; }
    }
    private int _idleArmy;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"idleArmy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int idleArmy
    {
      get { return _idleArmy; }
      set { _idleArmy = value; }
    }
    private int _maxHp_e;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"maxHp_e", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxHp_e
    {
      get { return _maxHp_e; }
      set { _maxHp_e = value; }
    }
    private int _hp_e;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"hp_e", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp_e
    {
      get { return _hp_e; }
      set { _hp_e = value; }
    }
    private int _maxMagic_e;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"maxMagic_e", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxMagic_e
    {
      get { return _maxMagic_e; }
      set { _maxMagic_e = value; }
    }
    private int _magic_e;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"magic_e", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magic_e
    {
      get { return _magic_e; }
      set { _magic_e = value; }
    }
    private int _idleArmy_e;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"idleArmy_e", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int idleArmy_e
    {
      get { return _idleArmy_e; }
      set { _idleArmy_e = value; }
    }
    private readonly global::System.Collections.Generic.List<BattleArmy> _battleArmys = new global::System.Collections.Generic.List<BattleArmy>();
    [global::ProtoBuf.ProtoMember(11, Name=@"battleArmys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BattleArmy> battleArmys
    {
      get { return _battleArmys; }
    }
  
    private readonly global::System.Collections.Generic.List<BattleArmy> _battleArmys_e = new global::System.Collections.Generic.List<BattleArmy>();
    [global::ProtoBuf.ProtoMember(12, Name=@"battleArmys_e", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BattleArmy> battleArmys_e
    {
      get { return _battleArmys_e; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleArmy")]
  public partial class BattleArmy : global::ProtoBuf.IExtensible
  {
    public BattleArmy() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _instanceId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"instanceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int instanceId
    {
      get { return _instanceId; }
      set { _instanceId = value; }
    }
    private int _armyColor;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"armyColor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int armyColor
    {
      get { return _armyColor; }
      set { _armyColor = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveArmyReq")]
  public partial class MoveArmyReq : global::ProtoBuf.IExtensible
  {
    public MoveArmyReq() {}
    
    private int _fromx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fromx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromx
    {
      get { return _fromx; }
      set { _fromx = value; }
    }
    private int _tox;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tox", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tox
    {
      get { return _tox; }
      set { _tox = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveArmyReq")]
  public partial class RemoveArmyReq : global::ProtoBuf.IExtensible
  {
    public RemoveArmyReq() {}
    
    private int _targetx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"targetx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetx
    {
      get { return _targetx; }
      set { _targetx = value; }
    }
    private int _targety;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"targety", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targety
    {
      get { return _targety; }
      set { _targety = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerAtkReq")]
  public partial class PlayerAtkReq : global::ProtoBuf.IExtensible
  {
    public PlayerAtkReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleChangeSyn")]
  public partial class BattleChangeSyn : global::ProtoBuf.IExtensible
  {
    public BattleChangeSyn() {}
    
    private readonly global::System.Collections.Generic.List<BattleStepMessage> _battleStep = new global::System.Collections.Generic.List<BattleStepMessage>();
    [global::ProtoBuf.ProtoMember(1, Name=@"battleStep", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BattleStepMessage> battleStep
    {
      get { return _battleStep; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleStepMessage")]
  public partial class BattleStepMessage : global::ProtoBuf.IExtensible
  {
    public BattleStepMessage() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ArmyMoveMessage _armyMove = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"armyMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ArmyMoveMessage armyMove
    {
      get { return _armyMove; }
      set { _armyMove = value; }
    }
    private AtkQueueMessage _atkqueue = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"atkqueue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AtkQueueMessage atkqueue
    {
      get { return _atkqueue; }
      set { _atkqueue = value; }
    }
    private WallQueueMessage _wallQueue = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wallQueue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WallQueueMessage wallQueue
    {
      get { return _wallQueue; }
      set { _wallQueue = value; }
    }
    private WallMergeMessage _wallMerge = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wallMerge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WallMergeMessage wallMerge
    {
      get { return _wallMerge; }
      set { _wallMerge = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArmyMoveMessage")]
  public partial class ArmyMoveMessage : global::ProtoBuf.IExtensible
  {
    public ArmyMoveMessage() {}
    
    private int _armyId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"armyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int armyId
    {
      get { return _armyId; }
      set { _armyId = value; }
    }
    private int _tox;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tox", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tox
    {
      get { return _tox; }
      set { _tox = value; }
    }
    private int _toy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"toy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toy
    {
      get { return _toy; }
      set { _toy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AtkQueueMessage")]
  public partial class AtkQueueMessage : global::ProtoBuf.IExtensible
  {
    public AtkQueueMessage() {}
    
    private readonly global::System.Collections.Generic.List<int> _armyId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"armyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> armyId
    {
      get { return _armyId; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _targetY = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"targetY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> targetY
    {
      get { return _targetY; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WallQueueMessage")]
  public partial class WallQueueMessage : global::ProtoBuf.IExtensible
  {
    public WallQueueMessage() {}
    
    private readonly global::System.Collections.Generic.List<int> _armyId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"armyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> armyId
    {
      get { return _armyId; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _targetX = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"targetX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> targetX
    {
      get { return _targetX; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _targetY = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"targetY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> targetY
    {
      get { return _targetY; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WallMergeMessage")]
  public partial class WallMergeMessage : global::ProtoBuf.IExtensible
  {
    public WallMergeMessage() {}
    
    private readonly global::System.Collections.Generic.List<int> _fromId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fromId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> fromId
    {
      get { return _fromId; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _toId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"toId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> toId
    {
      get { return _toId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}