//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: light framework (CF/Silverlight) enabled
    
// Generated from: Message.proto
namespace Message
{
  [global::ProtoBuf.ProtoContract(Name=@"RegistAccReq")]
  public partial class RegistAccReq : global::ProtoBuf.IExtensible
  {
    public RegistAccReq() {}
    
    private string _accName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accName
    {
      get { return _accName; }
      set { _accName = value; }
    }
	public string getaccName() { return _accName; }
	public void setaccName(string value) { _accName = value; }
	
    private string _passWord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passWord
    {
      get { return _passWord; }
      set { _passWord = value; }
    }
	public string getpassWord() { return _passWord; }
	public void setpassWord(string value) { _passWord = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"RegistAccRes")]
  public partial class RegistAccRes : global::ProtoBuf.IExtensible
  {
    public RegistAccRes() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
	public string gettoken() { return _token; }
	public void settoken(string value) { _token = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _accountName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accountName
    {
      get { return _accountName; }
      set { _accountName = value; }
    }
	public string getaccountName() { return _accountName; }
	public void setaccountName(string value) { _accountName = value; }
	
    private string _passWord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passWord
    {
      get { return _passWord; }
      set { _passWord = value; }
    }
	public string getpassWord() { return _passWord; }
	public void setpassWord(string value) { _passWord = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"LoginRes")]
  public partial class LoginRes : global::ProtoBuf.IExtensible
  {
    public LoginRes() {}
    
    private bool _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
	public bool getsuccess() { return _success; }
	public void setsuccess(bool value) { _success = value; }
	
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
	public string getreason() { return _reason; }
	public void setreason(string value) { _reason = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"GiveNameReq")]
  public partial class GiveNameReq : global::ProtoBuf.IExtensible
  {
    public GiveNameReq() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
	public string getname() { return _name; }
	public void setname(string value) { _name = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"GiveNameRes")]
  public partial class GiveNameRes : global::ProtoBuf.IExtensible
  {
    public GiveNameRes() {}
    
    private bool _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
	public bool getsuccess() { return _success; }
	public void setsuccess(bool value) { _success = value; }
	
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
	public string getreason() { return _reason; }
	public void setreason(string value) { _reason = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"HeadSetReq")]
  public partial class HeadSetReq : global::ProtoBuf.IExtensible
  {
    public HeadSetReq() {}
    
    private int _headId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"headId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headId
    {
      get { return _headId; }
      set { _headId = value; }
    }
	public int getheadId() { return _headId; }
	public void setheadId(int value) { _headId = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"HeadSetRes")]
  public partial class HeadSetRes : global::ProtoBuf.IExtensible
  {
    public HeadSetRes() {}
    
    private bool _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
	public bool getsuccess() { return _success; }
	public void setsuccess(bool value) { _success = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ApplyFriendReq")]
  public partial class ApplyFriendReq : global::ProtoBuf.IExtensible
  {
    public ApplyFriendReq() {}
    
    private int _friendId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int friendId
    {
      get { return _friendId; }
      set { _friendId = value; }
    }
	public int getfriendId() { return _friendId; }
	public void setfriendId(int value) { _friendId = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ApplyFriendRes")]
  public partial class ApplyFriendRes : global::ProtoBuf.IExtensible
  {
    public ApplyFriendRes() {}
    
    private bool _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
	public bool getsuccess() { return _success; }
	public void setsuccess(bool value) { _success = value; }
	
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
	public string getreason() { return _reason; }
	public void setreason(string value) { _reason = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"AgreeFriendReq")]
  public partial class AgreeFriendReq : global::ProtoBuf.IExtensible
  {
    public AgreeFriendReq() {}
    
    private int _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
	public int getroleId() { return _roleId; }
	public void setroleId(int value) { _roleId = value; }
	
    private bool _agree;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
	public bool getagree() { return _agree; }
	public void setagree(bool value) { _agree = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"AgreeFriendRes")]
  public partial class AgreeFriendRes : global::ProtoBuf.IExtensible
  {
    public AgreeFriendRes() {}
    
    private bool _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
	public bool getsuccess() { return _success; }
	public void setsuccess(bool value) { _success = value; }
	
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
	public string getreason() { return _reason; }
	public void setreason(string value) { _reason = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"FriendListReq")]
  public partial class FriendListReq : global::ProtoBuf.IExtensible
  {
    public FriendListReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"FriendListRes")]
  public partial class FriendListRes : global::ProtoBuf.IExtensible
  {
    public FriendListRes() {}
    
    private readonly global::System.Collections.Generic.List<FriendInfo> _friends = new global::System.Collections.Generic.List<FriendInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendInfo> friends
    {
      get { return _friends; }
    }
	public global::System.Collections.Generic.List<FriendInfo> getfriendsList() { return _friends; }
	public int getfriendsCount() { return _friends.Count; }
	public FriendInfo getfriends(int index) {return _friends[index]; }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"FriendInfo")]
  public partial class FriendInfo : global::ProtoBuf.IExtensible
  {
    public FriendInfo() {}
    
    private int _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
	public int getroleId() { return _roleId; }
	public void setroleId(int value) { _roleId = value; }
	
    private int _headId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"headId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int headId
    {
      get { return _headId; }
      set { _headId = value; }
    }
	public int getheadId() { return _headId; }
	public void setheadId(int value) { _headId = value; }
	
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}